using System.Collections.Generic;
using ComputerysBitStream.Attributes;
using ComputerysBitStream.Generator.Emission;

namespace ComputerysBitStream.Generator.Emitters;

internal readonly ref partial struct PrimitiveWrapperSourceEmitter {
    internal static string EmitSource(in PrimitiveDefinition definition, PrimitiveDefinition? intHandler) {
        PrimitiveWrapperSourceEmitter emitter = new(definition, intHandler);
        return emitter.EmitSourceCore();
    }

    private readonly SourceWriter _writer;
    private readonly PrimitiveDefinition _definition;

    private readonly string _alias;
    private readonly string _pluralAlias;
    private readonly string _targetType;
    private readonly string _extensionClass;
    private readonly string[] _additionalUsings;
    private readonly PrimitiveSerializationMode _mode;
    private readonly string _extraParams;
    private readonly string _extraArgs;
    private readonly string _extraArgsPrefix;
    private readonly bool _hasIntWrite;
    private readonly bool _hasIntPeek;
    private readonly string _intExtensionClass;
    private readonly string _intWriteMethodName;
    private readonly string _intPeekMethodName;
    private readonly int _intSize;

    private PrimitiveWrapperSourceEmitter(in PrimitiveDefinition definition, PrimitiveDefinition? intHandler) {
        _definition = definition;
        _alias = definition.Alias;
        _pluralAlias = $"{definition.Alias}s";
        _targetType = definition.TargetTypeEmitName;
        _mode = definition.Mode;

        string? generatedNamespaceName = definition.Namespace;
        List<string> additionalUsings = [];
        GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, definition.TargetTypeNamespace, generatedNamespaceName);
        _extensionClass = GeneratedSourceSyntax.QualifyTypeReference(generatedNamespaceName, definition.ExtensionClassFullyQualifiedName, additionalUsings);
        string intExtensionClass = "";
        string intWriteMethodName = "";
        string intPeekMethodName = "";
        int intSize = 0;
        bool hasIntWrite = false;
        bool hasIntPeek = false;
        if (intHandler is PrimitiveDefinition handler) {
            GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, handler.Namespace, generatedNamespaceName);
            intExtensionClass = GeneratedSourceSyntax.QualifyTypeReference(generatedNamespaceName, handler.ExtensionClassFullyQualifiedName, additionalUsings);
            intSize = handler.FixedSize ?? 0;
            if (HasValidMethod(handler, BitStreamPrimitiveRole.Write)) {
                hasIntWrite = true;
                intWriteMethodName = handler.Methods[BitStreamPrimitiveRole.Write].MethodName;
            }
            if (HasValidMethod(handler, BitStreamPrimitiveRole.Peek)) {
                hasIntPeek = true;
                intPeekMethodName = handler.Methods[BitStreamPrimitiveRole.Peek].MethodName;
            }
        }

        _additionalUsings = additionalUsings.ToArray();
        _intExtensionClass = intExtensionClass;
        _intWriteMethodName = intWriteMethodName;
        _intPeekMethodName = intPeekMethodName;
        _intSize = intSize;
        _hasIntWrite = hasIntWrite;
        _hasIntPeek = hasIntPeek;

        bool isQuantized = _mode == PrimitiveSerializationMode.Quantized;
        _extraParams = isQuantized ? $", {_targetType} min, {_targetType} max, int bitCount" : "";
        _extraArgs = isQuantized ? ", min, max, bitCount" : "";
        _extraArgsPrefix = isQuantized ? "min, max, bitCount, " : "";
        _writer = new SourceWriter();
    }

    private string EmitSourceCore() {
        _writer.WriteLine("// <auto-generated/>");
        _writer.WriteLine();
        GeneratedSourceSyntax.EmitStandardUsings(_writer, _additionalUsings);

        string? namespaceName = _definition.Namespace;
        if (namespaceName is not null) {
            _writer.WriteLine($"namespace {namespaceName} {{");
            _writer.Indent++;
        }

        EmitWriteContextClass();
        EmitReadContextClass();
        EmitSizeClass();

        if (namespaceName is not null) {
            _writer.Indent--;
            _writer.WriteLine("}");
        }

        return _writer.ToString();
    }

    public static bool HasValidMethod(in PrimitiveDefinition definition, BitStreamPrimitiveRole role) => definition.Methods.TryGetValue(role, out PrimitiveMethodDefinition method) && method.IsValid;
    private bool Has(BitStreamPrimitiveRole role) => HasValidMethod(_definition, role);
    private string Method(BitStreamPrimitiveRole role) => _definition.Methods[role].MethodName;
    private int FixedSize => _definition.FixedSize ?? 0;
    private int MinBits => _definition.MinBits ?? 1;
    private int MaxBits => _definition.MaxBits ?? 64;
    private bool IsQuantized => _mode == PrimitiveSerializationMode.Quantized;
    private string BitCountValidationThrow => $"if (bitCount < {MinBits} || bitCount > {MaxBits}) {{ throw new ArgumentOutOfRangeException(nameof(bitCount), bitCount, \"Bit count must be between {MinBits} and {MaxBits}.\"); }}";
    private string QuantizedFailPrefix => IsQuantized ? $"bitCount < {MinBits} || bitCount > {MaxBits} || " : "";

    private string QuantizedBitCountValidationPrefix() {
        return IsQuantized
            ? $$"""
                {{BitCountValidationThrow}}
                """
            : "";
    }

    private string EmitThrowIfTryReadFailedBody(string typeName, string tryExpression, string successBody) {
        if (!IsQuantized) { return GeneratedSourceSyntax.EmitThrowIfTryReadFailed(typeName, tryExpression, successBody); }

        return $$"""
                 {{BitCountValidationThrow}}
                 {{GeneratedSourceSyntax.EmitThrowIfTryReadFailed(typeName, tryExpression, successBody)}}
                 """;
    }

    private string SingleReadFailCondition => _mode switch {
        PrimitiveSerializationMode.Quantized => $"{QuantizedFailPrefix}context.IsInsufficientSpace(bitCount)", _ => $"context.IsInsufficientSpace({FixedSize})"
    };

    private string PerElementBits(string countExpression) => _mode switch {
        PrimitiveSerializationMode.Quantized => $"(long){countExpression} * bitCount", _ => $"(long){countExpression} * {FixedSize}"
    };

    private string TargetTypeArray => _targetType + "[]";

    private string TryPeekScalarCall() => $"context.TryPeek{_alias}({_extraArgsPrefix}out {_targetType} value)";

    private string TryReadScalarCall() => $"context.TryRead{_alias}({_extraArgsPrefix}out {_targetType} value)";

    private string TryPeekArrayCall() => $"context.TryPeek{_pluralAlias}({_extraArgsPrefix}out {TargetTypeArray} values)";

    private string TryReadArrayCall() => $"context.TryRead{_pluralAlias}({_extraArgsPrefix}out {TargetTypeArray} values)";

    private string TryPeekArrayWithCountCall() => $"context.TryPeek{_pluralAlias}(count{_extraArgs}, out {TargetTypeArray} values)";

    private string TryReadArrayWithCountCall() => $"context.TryRead{_pluralAlias}(count{_extraArgs}, out {TargetTypeArray} values)";

    private string TryPeekSpanCall() => $"context.TryPeek{_pluralAlias}(destination{_extraArgs})";

    private string TryReadSpanCall() => $"context.TryRead{_pluralAlias}(destination{_extraArgs})";

    private string TryPeekSpanWithCountCall() => $"context.TryPeek{_pluralAlias}(count, destination{_extraArgs})";

    private string TryReadSpanWithCountCall() => $"context.TryRead{_pluralAlias}(count, destination{_extraArgs})";

    private string TryPeekArrayWithMaxCountCall() => $"context.TryPeek{_pluralAlias}WithMaxCount(maxCount{_extraArgs}, out {TargetTypeArray} values)";

    private string TryReadArrayWithMaxCountCall() => $"context.TryRead{_pluralAlias}WithMaxCount(maxCount{_extraArgs}, out {TargetTypeArray} values)";

    private string TryPeekSpanWithMaxCountCall() => $"context.TryPeek{_pluralAlias}WithMaxCount(maxCount, destination{_extraArgs})";

    private string TryReadSpanWithMaxCountCall() => $"context.TryRead{_pluralAlias}WithMaxCount(maxCount, destination{_extraArgs})";
}
