<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <DefineConstants>$(DefineConstants);COMPUTERYS_BITSTREAM_GENERATOR</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" PrivateAssets="all" />
        <PackageReference Include="System.Memory" Version="4.6.3" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\ComputerysBitStream\Attributes.cs" Link="ComputerysBitStream\Attributes.cs" />
        <Compile Include="..\ComputerysBitStream\DefaultSettings.cs" Link="ComputerysBitStream\DefaultSettings.cs" />
        <Compile Include="..\ComputerysBitStream\BitHelper.cs" Link="ComputerysBitStream\BitHelper.cs" />
        <Compile Include="..\ComputerysBitStream\WriteContext.cs" Link="ComputerysBitStream\WriteContext.cs" />
        <Compile Include="..\ComputerysBitStream\ReadContext.cs" Link="ComputerysBitStream\ReadContext.cs" />
    </ItemGroup>
</Project>
