using System.Collections.Generic;
using ComputerysBitStream.Attributes;

namespace ComputerysBitStream.Generator.Emitters;

internal readonly ref partial struct StructPrimitiveSourceEmitter {
    internal static string EmitSource(in ResolvedStructDefinition resolved) {
        StructPrimitiveSourceEmitter emitter = new(resolved);
        return emitter.EmitSourceCore();
    }

    private readonly ResolvedStructDefinition _resolved;
    private readonly string _alias;
    private readonly string _targetType;
    private readonly string _generatedNamespace;
    private readonly string[] _additionalUsings;
    private readonly PrimitiveSerializationMode _mode;
    private readonly EquatableImmutableArray<ResolvedStructMember> _members;

    private StructPrimitiveSourceEmitter(in ResolvedStructDefinition resolved) {
        _resolved = resolved;
        StructDefinition source = resolved.Source;
        _alias = source.Alias;
        _targetType = StructPrimitiveDefinitionFactory.GetEmitTypeName(source.TypeFullyQualifiedName);
        _generatedNamespace = source.Namespace ?? nameof(ComputerysBitStream);
        _mode = resolved.Mode;
        _members = resolved.Members;

        List<string> additionalUsings = [];
        GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, GeneratedSourceSyntax.GetNamespaceFromFullyQualifiedName(source.TypeFullyQualifiedName), _generatedNamespace);
        foreach (string requiredUsing in resolved.RequiredUsings) { GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, requiredUsing, _generatedNamespace); }
        foreach (ResolvedStructMember member in resolved.Members) {
            GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, GeneratedSourceSyntax.GetNamespaceFromFullyQualifiedName(member.TypeFullyQualifiedName), _generatedNamespace);
        }

        _additionalUsings = additionalUsings.ToArray();
    }

    private string EmitSourceCore() {
        SourceWriter writer = new();

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine();
        GeneratedSourceSyntax.EmitStandardUsings(writer, _additionalUsings);

        writer.WriteLine($"namespace {_generatedNamespace} {{");
        writer.Indent++;
        writer.WriteLine($"public static class {_alias}StructPrimitiveExtensions {{");
        writer.Indent++;

        EmitWriteMethods(writer);
        EmitReadMethods(writer);
        EmitVariableLengthMethods(writer);

        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        return writer.ToString();
    }

    public static bool HasValidMethod(in ResolvedStructDefinition resolved, BitStreamPrimitiveRole role) {
        return resolved.Methods.TryGetValue(role, out PrimitiveMethodDefinition method) && method.IsValid;
    }

    private bool Has(BitStreamPrimitiveRole role) => HasValidMethod(_resolved, role);
    private string Method(BitStreamPrimitiveRole role) => _resolved.Methods[role].MethodName;
    private bool IsFixedSize => _mode == PrimitiveSerializationMode.FixedSize;
    private int FixedSize => _resolved.FixedSize ?? 0;
}
