using ComputerysBitStream.Attributes;

namespace ComputerysBitStream.Generator.Emitters;

internal static class StructMetadataSourceEmitter {
    internal static string Emit(in ResolvedStructDefinition resolved) {
        int metadataSize = resolved.Mode == PrimitiveSerializationMode.VariableLength
            ? StructMetadataConstants.VariableLengthSize
            : resolved.FixedSize ?? 0;

        if (!StructMetadataConstants.IsValidSize(metadataSize)) { return string.Empty; }

        StructDefinition source = resolved.Source;
        string typeKind = source.IsProxyClass ? "static partial class" : "partial struct";
        string? namespaceName = source.Namespace;
        string typeName = source.DeclarationTypeEmitName;

        SourceWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine();
        writer.WriteLine("using ComputerysBitStream.Attributes;");
        writer.WriteLine();

        if (namespaceName is not null) {
            writer.WriteLine($"namespace {namespaceName} {{");
            writer.Indent++;
        }

        writer.WriteLine($"[BitStreamStructMetadata({metadataSize})]");
        writer.WriteLine($"{typeKind} {typeName} {{ }}");

        if (namespaceName is not null) {
            writer.Indent--;
            writer.WriteLine("}");
        }

        return writer.ToString();
    }
}
