using System.Collections.Generic;
using System.Collections.Immutable;
using ComputerysBitStream.Attributes;

namespace ComputerysBitStream.Generator.Emitters;

internal static class StructPrimitiveSourceEmitter {
    internal static string Emit(in ResolvedStructDefinition resolved) {
        StructDefinition source = resolved.Source;
        string alias = source.Alias;
        string generatedNamespace = source.Namespace ?? nameof(ComputerysBitStream);
        string targetTypeName = StructPrimitiveDefinitionFactory.GetEmitTypeName(source.TypeFullyQualifiedName);
        bool isFixedSize = resolved.Mode == PrimitiveSerializationMode.FixedSize;
        int fixedSize = resolved.FixedSize ?? 0;

        string writeMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.Write);
        string writeSpanMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.WriteSpan);
        string peekMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.Peek);
        string readMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.Read);
        string peekArrayMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.PeekArray);
        string readArrayMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.ReadArray);
        string peekSpanMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.PeekSpan);
        string readSpanMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.ReadSpan);
        string tryReadMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.TryRead);
        string sizeMethod = StructPrimitiveDefinitionFactory.GetMethodName(alias, BitStreamPrimitiveRole.Size);

        List<string> additionalUsings = [];
        GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, GeneratedSourceSyntax.GetNamespaceFromFullyQualifiedName(source.TypeFullyQualifiedName), generatedNamespace);
        foreach (string requiredUsing in resolved.RequiredUsings) {
            GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, requiredUsing, generatedNamespace);
        }
        foreach (ResolvedStructMember member in resolved.Members) {
            GeneratedSourceSyntax.CollectAdditionalUsings(
                additionalUsings,
                GeneratedSourceSyntax.GetNamespaceFromFullyQualifiedName(member.TypeFullyQualifiedName),
                generatedNamespace
            );
        }

        SourceWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine();
        GeneratedSourceSyntax.EmitStandardUsings(writer, additionalUsings.ToArray());

        writer.WriteLine($"namespace {generatedNamespace} {{");
        writer.Indent++;
        writer.WriteLine($"public static class {alias}StructPrimitiveExtensions {{");
        writer.Indent++;

        string writeBody = BuildWriteBody(resolved.Members);
        writer.WriteBlocks([
            $$"""
              [MethodImpl(MethodImplOptions.AggressiveInlining)]
              public static void {{writeMethod}}(this ref WriteContext context, {{targetTypeName}} value) {
                  {{SourceWriter.MaintainRelativeIndent(writeBody, 1)}}
              }
              """,
            $$"""
              [MethodImpl(MethodImplOptions.AggressiveInlining)]
              public static void {{writeSpanMethod}}(this ref WriteContext context, ReadOnlySpan<{{targetTypeName}}> values) {
                  for (int i = 0; i < values.Length; i++) {
                      {{writeMethod}}(ref context, values[i]);
                  }
              }
              """
        ]);
        writer.WriteLine();

        string peekBody = isFixedSize ? BuildFixedPeekBody(alias, targetTypeName, resolved.Members, fixedSize) : BuildVariablePositionScopedBody(alias, targetTypeName, resolved.Members, restorePosition: true);
        string readBody = isFixedSize ? BuildFixedReadBody(alias, targetTypeName, resolved.Members, fixedSize) : BuildVariablePositionScopedBody(alias, targetTypeName, resolved.Members, restorePosition: false);

        writer.WriteBlocks([
            $$"""
              [MethodImpl(MethodImplOptions.AggressiveInlining)]
              public static {{targetTypeName}} {{peekMethod}}(this ref ReadContext context) {
                  {{SourceWriter.MaintainRelativeIndent(peekBody, 1)}}
              }
              """,
            $$"""
              [MethodImpl(MethodImplOptions.AggressiveInlining)]
              public static {{targetTypeName}} {{readMethod}}(this ref ReadContext context) {
                  {{SourceWriter.MaintainRelativeIndent(readBody, 1)}}
              }
              """,
            $$"""
              [MethodImpl(MethodImplOptions.AggressiveInlining)]
              public static {{targetTypeName}}[] {{peekArrayMethod}}(this ref ReadContext context, int count) {
                  {{targetTypeName}}[] result = new {{targetTypeName}}[count];
                  {{peekSpanMethod}}(ref context, count, result);
                  return result;
              }
              """,
            $$"""
              [MethodImpl(MethodImplOptions.AggressiveInlining)]
              public static {{targetTypeName}}[] {{readArrayMethod}}(this ref ReadContext context, int count) {
                  {{targetTypeName}}[] result = new {{targetTypeName}}[count];
                  {{readSpanMethod}}(ref context, count, result);
                  return result;
              }
              """,
            $$"""
              [MethodImpl(MethodImplOptions.AggressiveInlining)]
              public static void {{peekSpanMethod}}(this ref ReadContext context, int count, Span<{{targetTypeName}}> destination) {
                  long originalPosition = context.Position;
                  {{readSpanMethod}}(ref context, count, destination);
                  context.Position = originalPosition;
              }
              """,
            $$"""
              [MethodImpl(MethodImplOptions.AggressiveInlining)]
              public static void {{readSpanMethod}}(this ref ReadContext context, int count, Span<{{targetTypeName}}> destination) {
                  Span<{{targetTypeName}}> destinationSlice = destination.Slice(0, count);
                  for (int i = 0; i < count; i++) {
                      destinationSlice[i] = {{readMethod}}(ref context);
                  }
              }
              """
        ]);

        if (!isFixedSize) {
            writer.WriteLine();
            string tryReadBody = BuildTryReadBody(targetTypeName, resolved.Members);
            string sizeBody = BuildSizeBody(resolved.Members);
            writer.WriteBlocks([
                $$"""
                  [MethodImpl(MethodImplOptions.AggressiveInlining)]
                  public static bool {{tryReadMethod}}(this ref ReadContext context, out {{targetTypeName}} value) {
                      {{SourceWriter.MaintainRelativeIndent(tryReadBody, 1)}}
                  }
                  """,
                $$"""
                  [MethodImpl(MethodImplOptions.AggressiveInlining)]
                  public static int {{sizeMethod}}({{targetTypeName}} value) {
                      return {{sizeBody}};
                  }
                  """
            ]);
        }

        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        return writer.ToString();
    }

    private static string BuildWriteBody(EquatableImmutableArray<ResolvedStructMember> members) {
        List<string> lines = [];
        foreach (ResolvedStructMember member in members) {
            lines.Add($"{member.WriteCall};");
        }
        return string.Join("\n", lines);
    }

    private static string BuildFixedPeekBody(string alias, string targetTypeName, EquatableImmutableArray<ResolvedStructMember> members, int fixedSize) {
        return $$"""
                 {{GeneratedSourceSyntax.EmitThrowInsufficientReadSpace(alias, fixedSize.ToString())}}
                 long originalPosition = context.Position;
                 {{targetTypeName}} result = new {{targetTypeName}} {
                 {{BuildObjectInitializer(members, useTempVariables: false)}}
                 };
                 context.Position = originalPosition;
                 return result;
                 """;
    }

    private static string BuildFixedReadBody(string alias, string targetTypeName, EquatableImmutableArray<ResolvedStructMember> members, int fixedSize) {
        return $$"""
                 {{GeneratedSourceSyntax.EmitThrowInsufficientReadSpace(alias, fixedSize.ToString())}}
                 return new {{targetTypeName}} {
                 {{BuildObjectInitializer(members, useTempVariables: false)}}
                 };
                 """;
    }

    private static void AddMemberTryReadLines(List<string> lines, ResolvedStructMember member, int memberIndex, string failureReturn) {
        string tempName = $"temp{memberIndex}";
        string tempDecl = $"{GeneratedSourceSyntax.GetShortTypeName(member.TypeFullyQualifiedName)} {tempName}";

        switch (member.TryRead.Kind) {
            case MemberTryReadKind.TryReadOut:
                lines.Add($"if (!{member.TryRead.TryReadCall}(ref context, out {tempDecl})) {{ context.Position = originalPosition; {failureReturn} }}");
                break;
            case MemberTryReadKind.PreflightThenRead:
                lines.Add($"if (context.IsInsufficientSpace({member.TryRead.FixedBits})) {{ context.Position = originalPosition; {failureReturn} }}");
                lines.Add($"{tempDecl} = {member.ReadExpression};");
                break;
        }
    }

    private static string BuildVariablePositionScopedBody(string alias, string targetTypeName, EquatableImmutableArray<ResolvedStructMember> members, bool restorePosition) {
        ImmutableArray<ResolvedStructMember> memberArray = members;
        string failureStatement = $"context.Position = originalPosition; {GeneratedSourceSyntax.EmitThrowReadFailed(alias)}";
        List<string> tryReadLines = [];
        for (int i = 0; i < memberArray.Length; i++) {
            AddMemberTryReadLines(tryReadLines, memberArray[i], i, failureStatement);
        }

        string tryReads = string.Join("\n", tryReadLines);
        string construct = BuildObjectInitializer(memberArray, useTempVariables: true);

        if (restorePosition) {
            return $$"""
                     long originalPosition = context.Position;
                     {{tryReads}}
                     {{targetTypeName}} result = new {{targetTypeName}} {
                     {{construct}}
                     };
                     context.Position = originalPosition;
                     return result;
                     """;
        }

        return $$"""
                 long originalPosition = context.Position;
                 {{tryReads}}
                 return new {{targetTypeName}} {
                 {{construct}}
                 };
                 """;
    }

    private static string BuildObjectInitializer(ImmutableArray<ResolvedStructMember> members, bool useTempVariables) {
        List<string> lines = [];
        for (int i = 0; i < members.Length; i++) {
            ResolvedStructMember member = members[i];
            string valueExpression = useTempVariables ? $"temp{i}" : member.ReadExpression;
            lines.Add($"    {member.MemberName} = {valueExpression}");
        }
        return string.Join(",\n", lines);
    }

    private static string BuildObjectInitializer(EquatableImmutableArray<ResolvedStructMember> members, bool useTempVariables) {
        return BuildObjectInitializer((ImmutableArray<ResolvedStructMember>)members, useTempVariables);
    }

    private static string BuildTryReadBody(string targetTypeName, EquatableImmutableArray<ResolvedStructMember> members) {
        ImmutableArray<ResolvedStructMember> memberArray = members;
        List<string> tryReadLines = [];
        for (int i = 0; i < memberArray.Length; i++) {
            AddMemberTryReadLines(tryReadLines, memberArray[i], i, "value = default; return false;");
        }

        string tryReads = string.Join("\n", tryReadLines);
        return $$"""
                 long originalPosition = context.Position;
                 {{tryReads}}
                 value = new {{targetTypeName}} {
                 {{BuildObjectInitializer(memberArray, useTempVariables: true)}}
                 };
                 return true;
                 """;
    }

    private static string BuildSizeBody(EquatableImmutableArray<ResolvedStructMember> members) {
        ImmutableArray<ResolvedStructMember> memberArray = members;
        if (memberArray.Length == 0) { return "0"; }
        List<string> parts = [];
        foreach (ResolvedStructMember member in memberArray) {
            parts.Add(member.SizeExpression);
        }
        return string.Join(" + ", parts);
    }
}
