using System.Collections.Generic;
using ComputerysBitStream.Attributes;
using ComputerysBitStream.Generator.Emission;
using ComputerysBitStream.Generator.EquatableCollections;

namespace ComputerysBitStream.Generator.Emitters;

internal readonly ref partial struct StructPrimitiveSourceEmitter {
    internal static string EmitSource(in ResolvedStructDefinition resolved) {
        StructPrimitiveSourceEmitter emitter = new(resolved);
        return emitter.EmitSourceCore();
    }

    private readonly SourceWriter _writer;
    private readonly ResolvedStructDefinition _resolved;
    private readonly string _alias;
    private readonly string _targetType;
    private readonly string _generatedNamespace;
    private readonly string[] _additionalUsings;
    private readonly PrimitiveSerializationMode _mode;
    private readonly EquatableImmutableArray<ResolvedStructMember> _members;

    private StructPrimitiveSourceEmitter(in ResolvedStructDefinition resolved) {
        _resolved = resolved;
        StructDefinition source = resolved.Source;
        _alias = source.Alias;
        _targetType = StructPrimitiveDefinitionFactory.GetEmitTypeName(source.TypeFullyQualifiedName);
        _generatedNamespace = source.Namespace ?? nameof(ComputerysBitStream);
        _mode = resolved.Mode;
        _members = resolved.Members;

        List<string> additionalUsings = [];
        GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, GeneratedSourceSyntax.GetNamespaceFromFullyQualifiedName(source.TypeFullyQualifiedName), _generatedNamespace);
        foreach (string requiredUsing in resolved.RequiredUsings) { GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, requiredUsing, _generatedNamespace); }
        foreach (ResolvedStructMember member in resolved.Members) {
            GeneratedSourceSyntax.CollectAdditionalUsings(additionalUsings, GeneratedSourceSyntax.GetNamespaceFromFullyQualifiedName(member.TypeFullyQualifiedName), _generatedNamespace);
        }

        _additionalUsings = additionalUsings.ToArray();
        _writer = new SourceWriter();
    }

    private string EmitSourceCore() {
        _writer.WriteLine("// <auto-generated/>");
        _writer.WriteLine();
        GeneratedSourceSyntax.EmitStandardUsings(_writer, _additionalUsings);

        _writer.WriteLine($"namespace {_generatedNamespace} {{");
        _writer.Indent++;
        _writer.WriteLine(GeneratedDocumentationSyntax.StructPrimitiveExtensionsClass);
        _writer.WriteLine($"public static class {_alias}StructPrimitiveExtensions {{");
        _writer.Indent++;

        EmitWriteMethods();
        EmitReadMethods();
        EmitVariableLengthMethods();
        EmitCollectionMethods();

        _writer.Indent--;
        _writer.WriteLine("}");
        _writer.Indent--;
        _writer.WriteLine("}");

        return _writer.ToString();
    }

    public static bool HasValidMethod(in ResolvedStructDefinition resolved, BitStreamPrimitiveRole role) {
        return resolved.Methods.TryGetValue(role, out PrimitiveMethodDefinition method) && method.IsValid;
    }

    private bool Has(BitStreamPrimitiveRole role) => HasValidMethod(_resolved, role);
    private string Method(BitStreamPrimitiveRole role) => _resolved.Methods[role].MethodName;
    private bool IsFixedSize => _mode == PrimitiveSerializationMode.FixedSize;
    private int FixedSize => _resolved.FixedSize ?? 0;
}
